"""add_audit_trail_to_personnel

Revision ID: bef66a2a675e
Revises:
Create Date: 2026-05-10 06:16:46.504472

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bef66a2a675e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_levels",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("level_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_access_levels_id"), "access_levels", ["id"], unique=False)
    op.create_index(
        op.f("ix_access_levels_level_order"),
        "access_levels",
        ["level_order"],
        unique=True,
    )
    op.create_index(
        op.f("ix_access_levels_name"), "access_levels", ["name"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "active", "suspended", "unrecognised", name="user_status"
            ),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum("super_admin", "admin", "user", name="user_role"),
            nullable=False,
        ),
        sa.Column("access_level_id", sa.String(length=36), nullable=True),
        sa.Column("first_sign_in_at", sa.DateTime(), nullable=True),
        sa.Column("last_sign_in_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["access_level_id"],
            ["access_levels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column(
            "entity_type",
            sa.Enum(
                "attendance",
                "deployment",
                "session",
                "user",
                "csv_upload",
                "estab",
                "personnel",
                "access_level",
                "column_mapping",
                name="audit_entity_type",
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "create",
                "update",
                "delete",
                "archive",
                "close",
                "finalize",
                name="audit_action",
            ),
            nullable=False,
        ),
        sa.Column("changes", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_entity_type"), "audit_logs", ["entity_type"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_timestamp"), "audit_logs", ["timestamp"], unique=False
    )
    op.create_table(
        "column_mappings",
        sa.Column("raw_name", sa.String(length=255), nullable=False),
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "auto_detected",
                "admin_confirmed",
                "deprecated",
                name="column_mapping_status",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("confirmed_by", sa.String(length=36), nullable=True),
        sa.Column("deprecated_at", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["confirmed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_column_mappings_canonical_name"),
        "column_mappings",
        ["canonical_name"],
        unique=True,
    )
    op.create_index(
        op.f("ix_column_mappings_id"), "column_mappings", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_column_mappings_raw_name"),
        "column_mappings",
        ["raw_name"],
        unique=False,
    )
    op.create_table(
        "estabs",
        sa.Column("caa", sa.Date(), nullable=False),
        sa.Column("csv_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "confirmed", "archived", name="estab_status"),
            nullable=False,
        ),
        sa.Column("personnel_count", sa.Integer(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.Column("uploaded_by", sa.String(length=36), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("confirmed_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["confirmed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_estabs_caa"), "estabs", ["caa"], unique=True)
    op.create_index(op.f("ix_estabs_csv_hash"), "estabs", ["csv_hash"], unique=False)
    op.create_index(op.f("ix_estabs_id"), "estabs", ["id"], unique=False)
    op.create_table(
        "user_sessions",
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(), nullable=False),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token", "id"),
    )
    op.create_index(
        "ix_user_sessions_expires_at", "user_sessions", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_user_sessions_id"), "user_sessions", ["id"], unique=False)
    op.create_index(
        "ix_user_sessions_user_id", "user_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "csv_uploads",
        sa.Column("estab_id", sa.String(length=36), nullable=True),
        sa.Column("raw_content", sa.LargeBinary(), nullable=False),
        sa.Column("sha256_hash", sa.String(length=64), nullable=False),
        sa.Column("line_count", sa.Integer(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.Column("uploaded_by", sa.String(length=36), nullable=False),
        sa.Column("mapping_confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("diff_confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "received",
                "mapping_confirmed",
                "diff_confirmed",
                "failed",
                name="csv_upload_status",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["estab_id"],
            ["estabs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_csv_uploads_id"), "csv_uploads", ["id"], unique=False)
    op.create_index(
        op.f("ix_csv_uploads_sha256_hash"), "csv_uploads", ["sha256_hash"], unique=True
    )
    op.create_table(
        "deployments",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("estab_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "active",
                "inactive",
                "archived",
                "closed",
                "finalized",
                name="deployment_status",
            ),
            nullable=False,
        ),
        sa.Column("valid_from", sa.DateTime(), nullable=False),
        sa.Column("valid_until", sa.DateTime(), nullable=False),
        sa.Column("scheduled_activation", sa.DateTime(), nullable=True),
        sa.Column("personnel_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("activated_at", sa.DateTime(), nullable=True),
        sa.Column("deactivated_at", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["estab_id"], ["estabs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_deployments_id"), "deployments", ["id"], unique=False)
    op.create_table(
        "personnel",
        sa.Column("estab_id", sa.String(length=36), nullable=False),
        sa.Column("pers_no", sa.String(length=255), nullable=False),
        sa.Column("rank", sa.String(length=50), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("unit", sa.String(length=255), nullable=False),
        sa.Column("sub_unit_1", sa.String(length=255), nullable=True),
        sa.Column("sub_unit_2", sa.String(length=255), nullable=True),
        sa.Column("sub_unit_3", sa.String(length=255), nullable=True),
        sa.Column("extra_fields", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "archived", name="personnel_status"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["estab_id"], ["estabs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_personnel_estab_id"), "personnel", ["estab_id"], unique=False
    )
    op.create_index(op.f("ix_personnel_id"), "personnel", ["id"], unique=False)
    op.create_index(
        op.f("ix_personnel_pers_no"), "personnel", ["pers_no"], unique=False
    )
    op.create_table(
        "column_metadata",
        sa.Column("estab_id", sa.String(length=36), nullable=False),
        sa.Column("csv_upload_id", sa.String(length=36), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("canonical_name", sa.String(length=255), nullable=True),
        sa.Column(
            "inferred_type",
            sa.Enum(
                "string", "integer", "date", "boolean", "json", name="column_data_type"
            ),
            nullable=False,
        ),
        sa.Column("sensitivity_level_id", sa.String(length=36), nullable=True),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["csv_upload_id"], ["csv_uploads.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["estab_id"], ["estabs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["sensitivity_level_id"],
            ["access_levels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("estab_id", "original_name", name="unique_estab_column"),
    )
    op.create_index(
        op.f("ix_column_metadata_id"), "column_metadata", ["id"], unique=False
    )
    op.create_table(
        "deployment_notes",
        sa.Column("deployment_id", sa.String(length=36), nullable=False),
        sa.Column("personnel_id", sa.String(length=36), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=False),
        sa.Column("notes_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deployment_id"], ["deployments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["personnel_id"], ["personnel.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "deployment_id", "personnel_id", name="unique_deployment_personnel_notes"
        ),
    )
    op.create_index(
        op.f("ix_deployment_notes_id"), "deployment_notes", ["id"], unique=False
    )
    op.create_table(
        "deployment_personnel_overrides",
        sa.Column("deployment_id", sa.String(length=36), nullable=False),
        sa.Column("personnel_id", sa.String(length=36), nullable=False),
        sa.Column("unit", sa.String(length=255), nullable=False),
        sa.Column("sub_unit_1", sa.String(length=255), nullable=True),
        sa.Column("sub_unit_2", sa.String(length=255), nullable=True),
        sa.Column("sub_unit_3", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deployment_id"], ["deployments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["personnel_id"], ["personnel.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "deployment_id", "personnel_id", name="unique_deployment_personnel_override"
        ),
    )
    op.create_index(
        op.f("ix_deployment_personnel_overrides_id"),
        "deployment_personnel_overrides",
        ["id"],
        unique=False,
    )
    op.create_table(
        "deployment_user_accesses",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("deployment_id", sa.String(length=36), nullable=False),
        sa.Column("granted_by", sa.String(length=36), nullable=False),
        sa.Column("granted_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["deployment_id"], ["deployments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "deployment_id", name="unique_user_deployment_access"
        ),
    )
    op.create_index(
        op.f("ix_deployment_user_accesses_deployment_id"),
        "deployment_user_accesses",
        ["deployment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deployment_user_accesses_id"),
        "deployment_user_accesses",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deployment_user_accesses_user_id"),
        "deployment_user_accesses",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "sessions",
        sa.Column("deployment_id", sa.String(length=36), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "session_type", sa.Enum("AM", "PM", name="session_type"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("open", "closed", "finalized", name="session_status"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("opened_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("closed_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["closed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deployment_id"], ["deployments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "deployment_id",
            "date",
            "session_type",
            name="unique_deployment_date_session_type",
        ),
    )
    op.create_index(op.f("ix_sessions_date"), "sessions", ["date"], unique=False)
    op.create_index(op.f("ix_sessions_id"), "sessions", ["id"], unique=False)
    op.create_table(
        "user_subunit_scopes",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("deployment_id", sa.String(length=36), nullable=False),
        sa.Column("unit", sa.String(length=255), nullable=True),
        sa.Column("sub_unit_1", sa.String(length=255), nullable=True),
        sa.Column("sub_unit_2", sa.String(length=255), nullable=True),
        sa.Column("sub_unit_3", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deployment_id"], ["deployments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "deployment_id",
            "unit",
            "sub_unit_1",
            "sub_unit_2",
            "sub_unit_3",
            name="unique_user_deployment_scope",
        ),
    )
    op.create_index(
        op.f("ix_user_subunit_scopes_deployment_id"),
        "user_subunit_scopes",
        ["deployment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_subunit_scopes_id"), "user_subunit_scopes", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_user_subunit_scopes_user_id"),
        "user_subunit_scopes",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "attendance_records",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("personnel_id", sa.String(length=36), nullable=False),
        sa.Column("deployment_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "present", "absent", "excused", "unknown", name="attendance_status"
            ),
            nullable=False,
        ),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("notes_snapshot", sa.Text(), nullable=True),
        sa.Column("unit_snapshot", sa.String(length=255), nullable=True),
        sa.Column("sub_unit_1_snapshot", sa.String(length=255), nullable=True),
        sa.Column("sub_unit_2_snapshot", sa.String(length=255), nullable=True),
        sa.Column("sub_unit_3_snapshot", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=False),
        sa.Column("last_edit_at", sa.DateTime(), nullable=True),
        sa.Column("last_edit_by", sa.String(length=36), nullable=True),
        sa.Column("is_retroactive_edit", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deployment_id"], ["deployments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["last_edit_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["personnel_id"], ["personnel.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_id", "personnel_id", name="unique_session_personnel_attendance"
        ),
    )
    op.create_index(
        op.f("ix_attendance_records_id"), "attendance_records", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_attendance_records_id"), table_name="attendance_records")
    op.drop_table("attendance_records")
    op.drop_index(
        op.f("ix_user_subunit_scopes_user_id"), table_name="user_subunit_scopes"
    )
    op.drop_index(op.f("ix_user_subunit_scopes_id"), table_name="user_subunit_scopes")
    op.drop_index(
        op.f("ix_user_subunit_scopes_deployment_id"), table_name="user_subunit_scopes"
    )
    op.drop_table("user_subunit_scopes")
    op.drop_index(op.f("ix_sessions_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_date"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(
        op.f("ix_deployment_user_accesses_user_id"),
        table_name="deployment_user_accesses",
    )
    op.drop_index(
        op.f("ix_deployment_user_accesses_id"), table_name="deployment_user_accesses"
    )
    op.drop_index(
        op.f("ix_deployment_user_accesses_deployment_id"),
        table_name="deployment_user_accesses",
    )
    op.drop_table("deployment_user_accesses")
    op.drop_index(
        op.f("ix_deployment_personnel_overrides_id"),
        table_name="deployment_personnel_overrides",
    )
    op.drop_table("deployment_personnel_overrides")
    op.drop_index(op.f("ix_deployment_notes_id"), table_name="deployment_notes")
    op.drop_table("deployment_notes")
    op.drop_index(op.f("ix_column_metadata_id"), table_name="column_metadata")
    op.drop_table("column_metadata")
    op.drop_index(op.f("ix_personnel_pers_no"), table_name="personnel")
    op.drop_index(op.f("ix_personnel_id"), table_name="personnel")
    op.drop_index(op.f("ix_personnel_estab_id"), table_name="personnel")
    op.drop_table("personnel")
    op.drop_index(op.f("ix_deployments_id"), table_name="deployments")
    op.drop_table("deployments")
    op.drop_index(op.f("ix_csv_uploads_sha256_hash"), table_name="csv_uploads")
    op.drop_index(op.f("ix_csv_uploads_id"), table_name="csv_uploads")
    op.drop_table("csv_uploads")
    op.drop_index("ix_user_sessions_user_id", table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_id"), table_name="user_sessions")
    op.drop_index("ix_user_sessions_expires_at", table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index(op.f("ix_estabs_id"), table_name="estabs")
    op.drop_index(op.f("ix_estabs_csv_hash"), table_name="estabs")
    op.drop_index(op.f("ix_estabs_caa"), table_name="estabs")
    op.drop_table("estabs")
    op.drop_index(op.f("ix_column_mappings_raw_name"), table_name="column_mappings")
    op.drop_index(op.f("ix_column_mappings_id"), table_name="column_mappings")
    op.drop_index(
        op.f("ix_column_mappings_canonical_name"), table_name="column_mappings"
    )
    op.drop_table("column_mappings")
    op.drop_index(op.f("ix_audit_logs_timestamp"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_access_levels_name"), table_name="access_levels")
    op.drop_index(op.f("ix_access_levels_level_order"), table_name="access_levels")
    op.drop_index(op.f("ix_access_levels_id"), table_name="access_levels")
    op.drop_table("access_levels")
    # ### end Alembic commands ###
